"""Vendoring: MANIFEST.sha256 drift check (strict in the vendored fry copy) and tools/vendor_gateway.py
behaviour (only where the tool exists, i.e. in ai-launchers)."""

import contextlib
import hashlib
import importlib.util
import io
import os
import shutil
import tempfile
import unittest

from ._pkg import PKG, REPO_ROOT, package_dir

TOOL = os.path.join(REPO_ROOT, "tools", "vendor_gateway.py")
SKIP_DIRS = {"__pycache__", ".mypy_cache", ".pytest_cache"}


def _files(root):
    out = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for f in filenames:
            if f == "MANIFEST.sha256" or f.endswith((".pyc", ".pyo")) or f in (".DS_Store", "Thumbs.db"):
                continue
            p = os.path.join(dirpath, f)
            out[os.path.relpath(p, root).replace(os.sep, "/")] = p
    return out


def _manifest_problems(root):
    mpath = os.path.join(root, "MANIFEST.sha256")
    if not os.path.isfile(mpath):
        return ["missing %s" % mpath]
    want = {}
    with open(mpath, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                digest, _, rel = line.rstrip("\n").partition("  ")
                want[rel] = digest
    have = _files(root)
    probs = []
    for rel in sorted(set(want) | set(have)):
        if rel not in have:
            probs.append("missing file %s" % rel)
        elif rel not in want:
            probs.append("unlisted file %s" % rel)
        else:
            with open(have[rel], "rb") as f:
                if hashlib.sha256(f.read()).hexdigest() != want[rel]:
                    probs.append("modified %s (edit ai-launchers/shared/gateway and re-vendor)" % rel)
    return probs


class ManifestDriftTests(unittest.TestCase):
    def test_vendored_copy_matches_manifest(self):
        if PKG == "shared.gateway":
            self.skipTest("canonical tree: MANIFEST.sha256 is regenerated by tools/vendor_gateway.py")
        self.assertEqual(_manifest_problems(package_dir()), [])
        self.assertEqual(_manifest_problems(os.path.dirname(os.path.abspath(__file__))), [])


def _load_tool():
    spec = importlib.util.spec_from_file_location("vendor_gateway_under_test", TOOL)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


@unittest.skipUnless(os.path.isfile(TOOL), "tools/vendor_gateway.py only exists in ai-launchers")
class VendorToolTests(unittest.TestCase):
    def setUp(self):
        self.tool = _load_tool()
        self.tmp = tempfile.mkdtemp(prefix="vendor-test-")
        self.src = os.path.join(self.tmp, "src")
        self.fry = os.path.join(self.tmp, "fry")
        os.makedirs(self.fry)
        self._w(self.src, "shared/gateway/__init__.py", b'__version__ = "1.0.0"\n')
        self._w(self.src, "shared/gateway/sub/mod.py", b"X = 1\r\n")  # CRLF preserved byte-for-byte
        self._w(self.src, "shared/gateway/DESIGN.md", b"# d\n")
        self._w(self.src, "shared/gateway/__pycache__/mod.cpython-38.pyc", b"junk")
        self._w(self.src, "tests/gateway/__init__.py", b"")
        self._w(self.src, "tests/gateway/_pkg.py", b'import os\n\nPKG = "shared.gateway"\n\ndef mod(): pass\n')
        self._w(self.src, "tests/gateway/test_a.py", b'from ._pkg import mod\nS = "shared.gateway"\n')

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _w(self, root, rel, data):
        p = os.path.join(root, *rel.split("/"))
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "wb") as f:
            f.write(data)

    def _r(self, root, rel):
        with open(os.path.join(root, *rel.split("/")), "rb") as f:
            return f.read()

    def _run(self, **kw):
        out = io.StringIO()
        rc = self.tool.vendor(self.fry, self.src, out=out, **kw)
        return rc, out.getvalue()

    def test_copy_rewrite_manifest(self):
        rc, out = self._run()
        self.assertEqual(rc, 0, out)
        self.assertEqual(self._r(self.fry, "fry_gateway/sub/mod.py"), b"X = 1\r\n")
        self.assertEqual(self._r(self.fry, "fry_gateway/__init__.py"), self._r(self.src, "shared/gateway/__init__.py"))
        self.assertFalse(os.path.exists(os.path.join(self.fry, "fry_gateway", "__pycache__")))
        self.assertEqual(self._r(self.fry, "tests/gateway/_pkg.py"),
                         b'import os\n\nPKG = "fry_gateway"\n\ndef mod(): pass\n')
        self.assertEqual(self._r(self.fry, "tests/gateway/test_a.py"), self._r(self.src, "tests/gateway/test_a.py"))
        self.assertEqual(self._r(self.fry, "tests/__init__.py"), b"")
        self.assertEqual(_manifest_problems(os.path.join(self.fry, "fry_gateway")), [])
        self.assertEqual(_manifest_problems(os.path.join(self.fry, "tests", "gateway")), [])
        self.assertEqual(self._r(self.fry, "fry_gateway/MANIFEST.sha256"),
                         self._r(self.src, "shared/gateway/MANIFEST.sha256"))
        self.assertNotIn(b"__pycache__", self._r(self.fry, "fry_gateway/MANIFEST.sha256"))
        self.assertEqual(self._run(check=True)[0], 0)
        rc, out = self._run()  # idempotent
        self.assertIn("0 file(s) written", out)

    def test_stale_deletion_and_check(self):
        self._run()
        os.remove(os.path.join(self.src, "shared", "gateway", "sub", "mod.py"))
        self._w(self.src, "shared/gateway/new.py", b"Y = 2\n")
        rc, out = self._run(check=True)
        self.assertEqual(rc, 1)
        self.assertIn("stale", out)
        rc, out = self._run(dry_run=True)
        self.assertEqual(rc, 0)
        self.assertTrue(os.path.exists(os.path.join(self.fry, "fry_gateway", "sub", "mod.py")), "dry run wrote")
        rc, out = self._run()
        self.assertEqual(rc, 0)
        self.assertFalse(os.path.exists(os.path.join(self.fry, "fry_gateway", "sub")))
        self.assertEqual(self._r(self.fry, "fry_gateway/new.py"), b"Y = 2\n")
        self.assertEqual(_manifest_problems(os.path.join(self.fry, "fry_gateway")), [])

    def test_refuses_local_edits_unless_forced(self):
        self._run()
        self._w(self.fry, "fry_gateway/sub/mod.py", b"hacked\n")
        self._w(self.fry, "tests/gateway/extra.py", b"")
        rc, out = self._run()
        self.assertEqual(rc, 2)
        self.assertIn("modified locally: sub/mod.py", out)
        self.assertIn("added locally: extra.py", out)
        self.assertEqual(self._r(self.fry, "fry_gateway/sub/mod.py"), b"hacked\n")
        rc, out = self._run(force=True)
        self.assertEqual(rc, 0)
        self.assertEqual(self._r(self.fry, "fry_gateway/sub/mod.py"), b"X = 1\r\n")
        self.assertFalse(os.path.exists(os.path.join(self.fry, "tests", "gateway", "extra.py")))

    def test_refuses_unmanaged_target_and_bad_pkg_line(self):
        self._w(self.fry, "fry_gateway/old.py", b"")
        rc, out = self._run()
        self.assertEqual(rc, 2)
        self.assertIn("without MANIFEST.sha256", out)
        shutil.rmtree(os.path.join(self.fry, "fry_gateway"))
        self._w(self.src, "tests/gateway/_pkg.py", b'PKG = "something.else"\n')
        with self.assertRaises(self.tool.VendorError):
            self._run()
        with contextlib.redirect_stderr(io.StringIO()) as err:
            self.assertEqual(self.tool.main([os.path.join(self.tmp, "missing"), "--src-root", self.src]), 2)
        self.assertIn("fry repo not found", err.getvalue())

    def test_real_tree_rewrite_line_present(self):
        """The real tests/gateway/_pkg.py must contain exactly one rewritable PKG line."""
        with open(os.path.join(REPO_ROOT, "tests", "gateway", "_pkg.py"), "rb") as f:
            contents = {"_pkg.py": f.read()}
        out = self.tool.rewrite_tests(contents)
        self.assertIn(b'PKG = "fry_gateway"', out["_pkg.py"])


if __name__ == "__main__":
    unittest.main()
