"""Fake CLI executables for tests (DESIGN §7): ``gcloud``, ``codex``, ``grok``, ``opencode``, ``op``.

``make_fake_bins(directory, **behaviour) -> directory`` writes a Python launcher per CLI (shebang =
this interpreter, mode 0755) plus a ``.cmd`` twin on Windows, a shared implementation and a
``fake_bins.json`` with the behaviour; prepend ``directory`` to ``PATH``. Every invocation appends
``{"bin", "argv", "stdin"}`` to ``calls.jsonl`` (``read_calls(directory, name=None)``);
``set_behaviour(directory, **changes)`` edits the behaviour of existing bins.

Supported commands and behaviour knobs (defaults in ``DEFAULTS``):
  ``gcloud auth application-default print-access-token``  -> ``gcloud_token`` (``gcloud_token_rc`` != 0
      prints ``gcloud_stderr`` and fails); ``gcloud config get-value project`` -> ``gcloud_project``
      (None -> "(unset)" on stderr); ``gcloud_delay`` seconds before answering.
  ``codex --version`` -> ``codex_version_output``; ``grok --version`` -> ``grok_version_output``.
  ``opencode run [--model M] ...`` reads the prompt from stdin, sleeps ``opencode_delay``, writes
      ``opencode_stderr``, exits ``opencode_rc`` if non-zero, else prints ``opencode_stdout`` verbatim
      or ``opencode_reply`` (wrapped in ANSI codes + a ``> build · M`` header when ``opencode_ansi``).
  ``op read <ref>`` -> ``op_values[ref]``; ``op_signed_in=False`` -> "not currently signed in" (rc 1);
      unknown ref -> rc 1; ``op_delay`` seconds before answering.
"""

import json
import os
import stat
import sys

from ..atomicio import atomic_write_bytes

__all__ = ["make_fake_bins", "set_behaviour", "read_calls", "BIN_NAMES", "DEFAULTS"]

BIN_NAMES = ("gcloud", "codex", "grok", "opencode", "op")
CONFIG_FILE = "fake_bins.json"
CALLS_FILE = "calls.jsonl"
IMPL_MODULE = "_fake_bin_impl"

DEFAULTS = {
    "gcloud_token": "ya29.fake-gcloud-token",
    "gcloud_token_rc": 0,
    "gcloud_stderr": "",
    "gcloud_project": "fake-gcloud-project",
    "gcloud_delay": 0.0,
    "codex_version_output": "codex-cli 0.160.0",
    "grok_version_output": "grok 1.0.0",
    "opencode_reply": "Hello from fake opencode.",
    "opencode_rc": 0,
    "opencode_stderr": "",
    "opencode_stdout": None,
    "opencode_delay": 0.0,
    "opencode_ansi": False,
    "op_values": {},
    "op_signed_in": True,
    "op_delay": 0.0,
}

_IMPL = r'''"""Shared implementation of the fake CLIs (generated by testing/fake_bins.py)."""
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))


def _out(text, stream=None):
    stream = stream or sys.stdout
    stream.buffer.write(text.encode("utf-8"))
    stream.flush()


def _err(text):
    _out(text, sys.stderr)


def _model(args):
    for i, a in enumerate(args):
        if a in ("--model", "-m") and i + 1 < len(args):
            return args[i + 1]
        if a.startswith("--model="):
            return a.split("=", 1)[1]
    return "default"


def gcloud(cfg, args, stdin):
    time.sleep(float(cfg["gcloud_delay"] or 0))
    if args[:3] == ["auth", "application-default", "print-access-token"]:
        if cfg["gcloud_token_rc"]:
            _err(cfg["gcloud_stderr"] or "ERROR: (gcloud.auth.application-default.print-access-token) "
                 "Please run:\n\n  $ gcloud auth application-default login\n")
            return int(cfg["gcloud_token_rc"])
        _out(cfg["gcloud_token"] + "\n")
        return 0
    if args[:3] == ["config", "get-value", "project"]:
        if cfg["gcloud_project"]:
            _out(cfg["gcloud_project"] + "\n")
        else:
            _err("(unset)\n")
        return 0
    if args[:1] == ["--version"]:
        _out("Google Cloud SDK 999.0.0\n")
        return 0
    _err("fake gcloud: unsupported arguments %r\n" % (args,))
    return 2


def _version(key):
    def run(cfg, args, stdin):
        if args[:1] in (["--version"], ["-V"]):
            _out(cfg[key] + "\n")
            return 0
        _err("fake cli: unsupported arguments %r\n" % (args,))
        return 2
    return run


def opencode(cfg, args, stdin):
    if args[:1] != ["run"]:
        _err("fake opencode: unsupported arguments %r\n" % (args,))
        return 2
    time.sleep(float(cfg["opencode_delay"] or 0))
    if cfg["opencode_stderr"]:
        _err(cfg["opencode_stderr"])
    if cfg["opencode_rc"]:
        return int(cfg["opencode_rc"])
    if cfg["opencode_stdout"] is not None:
        _out(cfg["opencode_stdout"])
    elif cfg["opencode_ansi"]:
        _out("\x1b[0m\n> build · %s\n\x1b[0m\n\x1b[1m%s\x1b[0m\n\x1b]0;opencode\x07" % (_model(args),
                                                                                     cfg["opencode_reply"]))
    else:
        _out(cfg["opencode_reply"] + "\n")
    return 0


def op(cfg, args, stdin):
    time.sleep(float(cfg["op_delay"] or 0))
    if args[:1] == ["read"] and len(args) >= 2:
        if not cfg["op_signed_in"]:
            _err("[ERROR] 2026/10/03 12:00:00 You are not currently signed in. Please run `op signin --help` "
                 "for instructions\n")
            return 1
        ref = [a for a in args[1:] if not a.startswith("-")][-1]
        value = (cfg["op_values"] or {}).get(ref)
        if value is None:
            _err("[ERROR] 2026/10/03 12:00:00 could not read secret: item not found\n")
            return 1
        _out(value + "\n")
        return 0
    if args[:1] == ["--version"]:
        _out("2.30.0\n")
        return 0
    _err("fake op: unsupported arguments %r\n" % (args,))
    return 2


HANDLERS = {"gcloud": gcloud, "codex": _version("codex_version_output"),
            "grok": _version("grok_version_output"), "opencode": opencode, "op": op}


def main(name):
    with open(os.path.join(HERE, "fake_bins.json"), "r", encoding="utf-8") as f:
        cfg = json.load(f)
    args = sys.argv[1:]
    stdin = sys.stdin.buffer.read().decode("utf-8", "replace") if name == "opencode" and args[:1] == ["run"] \
        else None
    line = json.dumps({"bin": name, "argv": args, "stdin": stdin, "pid": os.getpid()}) + "\n"
    with open(os.path.join(HERE, "calls.jsonl"), "a", encoding="utf-8") as f:
        f.write(line)
    sys.exit(HANDLERS[name](cfg, args, stdin))
'''

_LAUNCHER = """{shebang}
import os
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import {impl}  # noqa: E402

{impl}.main({name!r})
"""

_CMD = '@echo off\r\n"{python}" "%~dp0{name}" %*\r\nexit /b %ERRORLEVEL%\r\n'


def _shebang():
    exe = sys.executable or ""
    if exe and " " not in exe and len(exe) < 120:
        return "#!" + exe
    return "#!/usr/bin/env python3"


def _write(path, text, executable=False, newline="\n"):
    with open(path, "w", encoding="utf-8", newline=newline) as f:
        f.write(text)
    if executable:
        os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _check(behaviour):
    unknown = sorted(set(behaviour) - set(DEFAULTS))
    if unknown:
        raise TypeError("unknown fake-bin behaviour keys: %s" % ", ".join(unknown))


def make_fake_bins(directory, **behaviour):
    """Create the fake CLIs in ``directory`` (created if needed); returns ``directory``."""
    _check(behaviour)
    directory = os.path.abspath(os.fspath(directory))
    os.makedirs(directory, exist_ok=True)
    cfg = dict(DEFAULTS)
    cfg.update(behaviour)
    _write(os.path.join(directory, CONFIG_FILE), json.dumps(cfg, indent=2))
    _write(os.path.join(directory, IMPL_MODULE + ".py"), _IMPL)
    for name in BIN_NAMES:
        _write(os.path.join(directory, name), _LAUNCHER.format(shebang=_shebang(), impl=IMPL_MODULE, name=name),
               executable=True)
        if os.name == "nt":  # pragma: no cover - Windows only
            _write(os.path.join(directory, name + ".cmd"), _CMD.format(python=sys.executable, name=name),
                   newline="")
    return directory


def set_behaviour(directory, **changes):
    """Change the behaviour of bins created by ``make_fake_bins`` (takes effect on the next call)."""
    _check(changes)
    path = os.path.join(os.fspath(directory), CONFIG_FILE)
    with open(path, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    cfg.update(changes)
    atomic_write_bytes(path, json.dumps(cfg, indent=2).encode("utf-8"), mode=0o644)


def read_calls(directory, name=None):
    """Recorded invocations (dicts with ``bin``, ``argv``, ``stdin``), optionally for one CLI."""
    path = os.path.join(os.fspath(directory), CALLS_FILE)
    if not os.path.isfile(path):
        return []
    out = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rec = json.loads(line)
                if name is None or rec.get("bin") == name:
                    out.append(rec)
    return out
